FROM node:lts-alpine3.21

RUN apk add --no-cache vim openssl zsh git curl

WORKDIR /app

RUN npm install -g pnpm

# Configure PNPM environment
ENV PNPM_HOME=/root/.local/share/pnpm
ENV PATH=$PNPM_HOME:$PATH
RUN mkdir -p $PNPM_HOME

COPY pnpm-lock.yaml ./
COPY package.json ./

RUN pnpm install

RUN pnpm add -g contentful-cli

COPY . .

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

RUN git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

RUN echo "plugins=(git zsh-autosuggestions zsh-syntax-highlighting)" >> /root/.zshrc
RUN echo "source /root/.oh-my-zsh/oh-my-zsh.sh" >> /root/.zshrc
RUN echo "source ${ZSH_CUSTOM:-/root/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> /root/.zshrc


EXPOSE 5173

ENV NODE_ENV=development

CMD ["pnpm", "run", "dev", "--", "--host", "0.0.0.0"]

